### ISSUE TITLE
Evaluate XSense Android App

### ISSUE THREAD

**Issue by s4rify** [NeuropsyOL/SENDA#13]
.. and whether we can stream their data using our app in case we do not succeed in creating an LSL stream from XSense.

This issue will be assigned to Sören once he has a Github account.

**Comment by pmaanen** [comment]
SENDA can connect to and stream data from Movella DOT sensors. Advanced functionality like firmware updates, sensor renames etc. should stay in the official app, everything related to measurements should be implemented into SENDA.
